/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MenuItem,
} from '@menu-item';
import {
  Menu,
} from '@menu';

export namespace Components {
  interface SmuDemo {}
  interface SmuMenu {
    'collapsed': boolean;
    'collapsedTooltip': string;
    'dropdown': boolean;
    'getInstance': () => Promise<this>;
    'getItems': () => Promise<MenuItem[]>;
    'horizontal': boolean;
    'inline': boolean;
    'slug': string;
  }
  interface SmuMenuItem {
    'getInstance': () => Promise<this>;
    'icon': string;
    'index': string;
    'menu': Menu;
    'parentItem': Menu | MenuItem;
    'slug': string;
    'tag': string;
  }
  interface SmuMenuSubmenu {
    'dropdown': boolean;
    'getInstance': () => Promise<this>;
    'menu': Menu;
  }
}

declare global {


  interface HTMLSmuDemoElement extends Components.SmuDemo, HTMLStencilElement {}
  var HTMLSmuDemoElement: {
    prototype: HTMLSmuDemoElement;
    new (): HTMLSmuDemoElement;
  };

  interface HTMLSmuMenuElement extends Components.SmuMenu, HTMLStencilElement {}
  var HTMLSmuMenuElement: {
    prototype: HTMLSmuMenuElement;
    new (): HTMLSmuMenuElement;
  };

  interface HTMLSmuMenuItemElement extends Components.SmuMenuItem, HTMLStencilElement {}
  var HTMLSmuMenuItemElement: {
    prototype: HTMLSmuMenuItemElement;
    new (): HTMLSmuMenuItemElement;
  };

  interface HTMLSmuMenuSubmenuElement extends Components.SmuMenuSubmenu, HTMLStencilElement {}
  var HTMLSmuMenuSubmenuElement: {
    prototype: HTMLSmuMenuSubmenuElement;
    new (): HTMLSmuMenuSubmenuElement;
  };
  interface HTMLElementTagNameMap {
    'smu-demo': HTMLSmuDemoElement;
    'smu-menu': HTMLSmuMenuElement;
    'smu-menu-item': HTMLSmuMenuItemElement;
    'smu-menu-submenu': HTMLSmuMenuSubmenuElement;
  }
}

declare namespace LocalJSX {
  interface SmuDemo {}
  interface SmuMenu {
    'collapsed'?: boolean;
    'collapsedTooltip'?: string;
    'dropdown'?: boolean;
    'horizontal'?: boolean;
    'inline'?: boolean;
    'slug'?: string;
  }
  interface SmuMenuItem {
    'icon'?: string;
    'index'?: string;
    'menu'?: Menu;
    'onSmuMenuItemClicked'?: (event: CustomEvent<any>) => void;
    'onSmuMenuItemCollapsed'?: (event: CustomEvent<any>) => void;
    'onSmuMenuItemExpanded'?: (event: CustomEvent<any>) => void;
    'onSmuMenuItemFocused'?: (event: CustomEvent<any>) => void;
    'onSmuMenuItemHovered'?: (event: CustomEvent<any>) => void;
    'onSmuMenuItemSelected'?: (event: CustomEvent<any>) => void;
    'onSmuMenuItemToggled'?: (event: CustomEvent<any>) => void;
    'parentItem'?: Menu | MenuItem;
    'slug'?: string;
    'tag'?: string;
  }
  interface SmuMenuSubmenu {
    'dropdown'?: boolean;
    'menu'?: Menu;
  }

  interface IntrinsicElements {
    'smu-demo': SmuDemo;
    'smu-menu': SmuMenu;
    'smu-menu-item': SmuMenuItem;
    'smu-menu-submenu': SmuMenuSubmenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'smu-demo': LocalJSX.SmuDemo & JSXBase.HTMLAttributes<HTMLSmuDemoElement>;
      'smu-menu': LocalJSX.SmuMenu & JSXBase.HTMLAttributes<HTMLSmuMenuElement>;
      'smu-menu-item': LocalJSX.SmuMenuItem & JSXBase.HTMLAttributes<HTMLSmuMenuItemElement>;
      'smu-menu-submenu': LocalJSX.SmuMenuSubmenu & JSXBase.HTMLAttributes<HTMLSmuMenuSubmenuElement>;
    }
  }
}


