
server {
	listen 80;
    listen 443 ssl http2;
	server_name template.local;

    error_log /tmp/template/logs/error.log;
    access_log /tmp/template/logs/access.log;

	root /tmp/template;
    index index.php index.html;

    charset utf-8;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    error_page 404 /index.php;

    # This configuration prevent the logger to log not found favicon
    location = /favicon.ico {
            log_not_found off;
            access_log off;
    }

    # Same as favicon but for robots.txt
    location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
    }


    location / {
        #try_files $uri $uri/ /index.php?$is_args$args; # This says the Nginx server to rewrite any requests which do not access a valid file to rewrite on to the index.php
        try_files $uri $uri/ /index.php?$query_string;
    }

    # This gets all requests from the location above and sends them to the php-fpm socket which will execute the php
    location ~ \.php$ {
            include fastcgi.conf;
            fastcgi_intercept_errors on;
            fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
    }

    # This says that all files with the given endings should be cached by the client
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            expires max;
            log_not_found off;
    }
}

