#!/bin/bash

each() {
    local cmd=$*
    cd packages
    for i in *; do
        yarn workspace @radic/$i $cmd
    done
    cd ..
}

on(){
    local name=$1
    shift
    local cmd=$*
    yarn workspace @radic/$name $cmd
}


$*