import { Options as BarOptions } from 'webpackbar';
import { Options as FriendlyErrorsOptions } from 'friendly-errors-webpack-plugin';
import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer';
import MiniCssExtractPlugin from 'mini-css-extract-plugin';
import { Options as CleanOptions } from 'clean-webpack-plugin';
import { Options as OptimizeCssAssetsOptions } from 'optimize-css-assets-webpack-plugin';
import { Options as HtmlOptions } from 'html-webpack-plugin';
import JsonPlugin from '../plugins/JsonPlugin';
import ScssVariableToTypescriptPlugin from '../plugins/ScssVariableToTypescriptPlugin';
import ExtraTemplatedPathsPlugin from '../plugins/ExtraTemplatedPathsPlugin';
export declare const entrypointPath: import("../interfaces").PluginBlockFunction<any>;
export declare const extraTemplatedPaths: import("../interfaces").PluginBlockFunction<ExtraTemplatedPathsPlugin.Options>;
export declare const json: import("../interfaces").PluginBlockFunction<JsonPlugin.Options>;
export declare const scss2ts: import("../interfaces").PluginBlockFunction<ScssVariableToTypescriptPlugin.Options>;
export declare const size: import("../interfaces").PluginBlockFunction<any>;
export declare const loaderOptions: import("../interfaces").PluginBlockFunction<any>;
export declare const copy: import("../interfaces").PluginBlockFunction<any>;
export declare const favicon: import("../interfaces").PluginBlockFunction<any>;
export declare const vueLoader: import("../interfaces").PluginBlockFunction<any>;
export declare const bar: import("../interfaces").PluginBlockFunction<BarOptions>;
export declare const friendlyErrors: import("../interfaces").PluginBlockFunction<FriendlyErrorsOptions>;
export declare const bundleAnalyzer: import("../interfaces").PluginBlockFunction<BundleAnalyzerPlugin.Options>;
export declare const miniCssExtract: import("../interfaces").PluginBlockFunction<MiniCssExtractPlugin.PluginOptions>;
export declare const MiniCssExtract: typeof MiniCssExtractPlugin;
export declare const clean: import("../interfaces").PluginBlockFunction<CleanOptions>;
export declare const define: import("../interfaces").PluginBlockFunction<any>;
export declare const html: import("../interfaces").PluginBlockFunction<HtmlOptions>;
export declare const optimizeCssAssets: import("../interfaces").PluginBlockFunction<OptimizeCssAssetsOptions>;
